### ISSUE TITLE
switch to ESM-only

### ISSUE THREAD

**Issue by jimmywarting** [hildjj/nofilter#10]
time to ditch cjs?

**Comment by hildjj** [comment]
Yep, it's time.  Next release will be node 16+, ES2021.

**Comment by jimmywarting** [comment]
May i help you make a PR?

**Comment by hildjj** [comment]
If you like.  I was going to switch to Typescript at the same time, and have it output plain es code, switch doc generation to typedoc, etc.

**Comment by jimmywarting** [comment]
>  I was going to switch to Typescript at the same time, 

hmm, then i will live it to ya. you can continue off from where i already started (#11)

- Updated all dependencies
- Test are working fine
- i have used typedoc on other plain checkJS allowJS project before and it works just fine.so i included that too

I don't like typescript syntax. rather prefer vanilla js, jsdoc and allowJs/check js without having to compile stuff that i think is harder to debug cuz it's not the original source code. sometimes it compiles to very much garbage code.

running instantly and being able to import original code/stuff from browser too is my jam
i go for cross compatible code when i code stuff.

sticking to jsdoc makes me a better developer for writing better comments

heck even wrote: https://jimmywarting.github.io/you-might-not-need-typescript/

So small npm packages dose not really need to be written in TS in my IMO

**Comment by hildjj** [comment]
I find your argument compelling.  I don't think we have any types that are complicated enough or need to be exported, which are the two things that often drive me over the Typescript cliff.

**Comment by jimmywarting** [comment]
fun fact, svelte v4 is switching back to plain vanilla js from having typescript
saw there youtube intervju yesterday 

https://www.youtube.com/live/MJHO6FSioPI?feature=share&t=96

**Comment by hildjj** [comment]
Fixed in #11, #12, and #13.
