### ISSUE TITLE
ReferenceError: TextDecoder is not defined

### ISSUE THREAD

**Issue by jweyrich** [hildjj/nofilter#7]
The commit https://github.com/hildjj/nofilter/commit/f4c359670034803936ebc790c5d107de15c3f839 broke on Node v10 - Yes, I know, nobody should still be using v10.
We have some pipelines that are still outdated due to the serverless framework version we're stuck with. These are still using node 10, and we're working on upgrading them. In the mean time, we'd be really happy if we could get it working again in node 10. Do you think that would be viable?

Here's a screenshot of what we got.

![image](https://user-images.githubusercontent.com/206930/138528710-5f2925e5-fd16-417b-b988-d04f07c5b30c.png)

Thank you!

**Comment by hildjj** [comment]
I'm tracking whatever needs to be done for this in https://github.com/hildjj/ctoaf-textdecoder
