### ISSUE TITLE
ReferenceError: TextDecoder is not defined

### ISSUE THREAD

**Issue by dchocoboo** [hildjj/nofilter#8]
Encountered this issue when using node18

    ReferenceError: TextDecoder is not defined

      at Object.<anonymous> (node_modules/nofilter/lib/index.js:5:12)

**Comment by hildjj** [comment]
TextDecoder is a global in node12+.  It's in util from node8 to  node10.  If you really need something, use https://github.com/hildjj/ctoaf-textdecoder

**Comment by hildjj** [comment]
Are you sure you're using Node18, and not NativeScript?

**Comment by hildjj** [comment]
Is this still an issue for you?

**Comment by hildjj** [comment]
Seeing no further comments, I'm guessing this isn't a problem anymore.  Please reopen if it is.
